# Generated by Django 5.1.2 on 2025-12-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(db_index=True, max_length=66, unique=True)),
                ('from_address', models.CharField(max_length=42)),
                ('to_address', models.CharField(max_length=42)),
                ('amount_raw', models.DecimalField(decimal_places=0, max_digits=36)),
                ('amount_token', models.DecimalField(decimal_places=6, max_digits=18)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('course', 'Course Payment'), ('supplier', 'Supplier Listing')], default='course', max_length=20)),
                ('token_contract', models.CharField(default='0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913', max_length=42)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('confirmations', models.IntegerField(default=0)),
                ('required_confirmations', models.IntegerField(default=2)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('org', models.CharField(default='tanya-client', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('gas_price', models.DecimalField(blank=True, decimal_places=0, max_digits=36, null=True)),
                ('gas_used', models.BigIntegerField(blank=True, null=True)),
                ('transfer_event_index', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_hash'], name='myApp_token_transac_c6a3f8_idx'), models.Index(fields=['status'], name='myApp_token_status_153404_idx'), models.Index(fields=['from_address'], name='myApp_token_from_ad_32038a_idx'), models.Index(fields=['payment_type'], name='myApp_token_payment_09c9ff_idx')],
            },
        ),
    ]
