# Generated by Django 5.1.2 on 2025-12-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenpayment',
            name='payment_type',
            field=models.CharField(choices=[('course', 'Course Payment'), ('supplier', 'Supplier Listing'), ('custom', 'Custom Amount')], default='course', max_length=20),
        ),
    ]
